version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: prodex_container
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - prodex-data:/data/db

volumes:
  prodex-data:
